import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateDocumentPDF = (doc: any, tabType: string) => {
  const customDoc = new jsPDF();
  
  // Set Title based on Document Type
  let title = "INVOICE";
  if (tabType === 'QUOTATIONS') title = "QUOTATION ESTIMATE";
  if (tabType === 'SALES_ORDERS') title = "SALES ORDER";
  if (tabType === 'DELIVERIES') title = "DELIVERY NOTE";
  
  // Purchases pipeline overrides
  if (tabType === 'REQUISITION') title = "PURCHASE REQUISITION (PR)";
  if (tabType === 'PURCHASE_ORDERS') title = "PURCHASE ORDER (PO)";
  if (tabType === 'GOODS_RECEIPT') title = "GOODS RECEIPT (GR)";
  if (tabType === 'VENDOR_BILLS') title = "VENDOR BILL";

  if (doc.status === 'CANCELLED') title = `VOIDED ${title}`;

  // Header
  customDoc.setFontSize(22);
  customDoc.setFont('helvetica', 'bold');
  customDoc.setTextColor(15, 59, 140); // Primary Blue
  customDoc.text("BizzCount ERP", 14, 22);

  customDoc.setFontSize(10);
  customDoc.setFont('helvetica', 'normal');
  customDoc.setTextColor(100, 100, 100);
  customDoc.text("123 Enterprise Avenue, Suite 400", 14, 28);
  customDoc.text("Jakarta, Indonesia 10220", 14, 33);
  customDoc.text("contact@bizzcount.dev | +62 800 1234 5678", 14, 38);

  // Document Info (Right side)
  customDoc.setFontSize(20);
  customDoc.setFont('helvetica', 'bold');
  customDoc.setTextColor(0, 0, 0);
  customDoc.text(title, 140, 22);

  customDoc.setFontSize(10);
  customDoc.setFont('helvetica', 'normal');
  customDoc.text(`Date: ${doc.date}`, 140, 30);
  customDoc.text(`Document #: ${doc.id}`, 140, 35);
  customDoc.text(`Status: ${doc.status}`, 140, 40);

  // Client / Vendor Info
  const isPurchase = ['REQUISITION', 'PURCHASE_ORDERS', 'GOODS_RECEIPT', 'VENDOR_BILLS'].includes(tabType);

  customDoc.setFontSize(12);
  customDoc.setFont('helvetica', 'bold');
  customDoc.setTextColor(0, 0, 0);
  customDoc.text(isPurchase ? "Requesting / Vendor Info:" : "Bill To:", 14, 55);
  customDoc.setFont('helvetica', 'normal');
  customDoc.text(doc.client, 14, 62);
  customDoc.text(isPurchase ? "Attn: Procurement & Warehouse" : "Attn: Accounts Payable", 14, 67);

  // Table Data (Mocked Line Items)
  const isFinancialValue = !['DELIVERIES', 'GOODS_RECEIPT'].includes(tabType);
  
  const tableData = [
    ["1", "Enterprise Software License - Annual", "1", doc.amount, doc.amount],
    ["2", "Implementation & Onboarding Support", "40", "$150.00", "$6,000.00"],
    ["3", "Cloud Server Allocation (TB)", "5", "$1,000.00", "$5,000.00"]
  ];

  autoTable(customDoc, {
    startY: 80,
    head: [['#', 'Description', 'Qty', 'Unit Price', 'Total Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [15, 59, 140], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [240, 248, 255] },
  });

  // Footer / Totals
  const finalY = (customDoc as any).lastAutoTable.finalY || 150;
  
  if (isFinancialValue) {
    customDoc.setFontSize(11);
    customDoc.setFont('helvetica', 'bold');
    customDoc.text(`Total Authorized Value: ${doc.amount}`, 130, finalY + 15);
  }

  customDoc.setFontSize(9);
  customDoc.setFont('helvetica', 'italic');
  customDoc.text("Thank you for your business. Generated by BizzCount Framework.", 14, finalY + 40);

  // Save the PDF
  customDoc.save(`${doc.id}_BizzCount.pdf`);
};
