version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bizzcount_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: bizzcount
    ports:
      - "5432:5432"
    volumes:
      - bizzcount_pgdata:/var/lib/postgresql/data

volumes:
  bizzcount_pgdata:
